RECORD_COL_NAME = "records"
RECORD_SIZE_COL_NAME = "record_size"
SIZE_GK = "size_gk"
COUNT_GK = "count_gk"

DEFAULT_MAX_RECORD_SIZE = 1 * 1024**2  # 1 MB
DEFAULT_MAX_BATCH_SIZE = 5 * 1024**2  # 5 MB
DEFAULT_MAX_NUM_RECORDS = 500
